### ISSUE TITLE
Unable to change the design and text of the Cancel & OK button

### ISSUE THREAD

**Issue by sajidfrommerqata** [ycs77/jquery-plugin-bsModal#3]
How I change the design and text of the Cancel & OK button of the pop-up?
![image](https://user-images.githubusercontent.com/66903912/99654528-e5cdaf80-2a73-11eb-9599-75d6f50b1f3c.png)

**Comment by ycs77** [comment]
In this package, the button colors are using the Bootstrap colors.

You can using `okBtn` / `cancelBtn` options:

(docs: https://github.com/ycs77/jquery-plugin-bsModal#okbtn)

```
$('#basicBtn').bsModal({
  id: 'bsModal',
  title: 'Title',
  body: 'Modal body text......',
  okBtn: {
    text: 'Delete',
    color: 'danger'
  },
  cancelBtn: {
    text: 'Back',
    color: 'info'
  }
});
```

![bsmodal](https://user-images.githubusercontent.com/38133356/99661247-8933ba00-2a9e-11eb-8634-18bc24c5ec18.jpg)

**Comment by sajidfrommerqata** [comment]
Thanks for your reply. you used **bsModal()** but I'm using **bsModalCropper()**.

```
$("#uploadImgBtn").bsModalCropper({
      id: "bsModalCropper",
      title: "Crop Image",
      okBtn: {
        text: "Crop Now",
        color: "primary",
      },
      onCancel: {
        text: "Cancel",
        color: "danger",
      },
      // Cropper.js options
      cropper: {
        aspectRatio: 1,
        zoomable: true,
        minCropBoxWidth: 100,
        minCropBoxHeight: 100,
      },

      // On cropper
      onCropper: function (dataURL) {
        props.setSrc(dataURL);
        props.setSrcName("Image Chosen");
        $("#cropedUploadImageBox").show();
        $("#cropedUploadImage").attr("src", dataURL);
      },

      uploadConfig: {
        maxSize: Math.pow(1024, 2) * 5, // 5M
      },
      onUploadError: function (error) {
        alert(error);
      },
    });
```

![image](https://user-images.githubusercontent.com/66903912/99709479-ac6b6300-2ab8-11eb-8c81-b67aadced665.png)

**Comment by ycs77** [comment]
Sorry, the cropper model (comfirm mode) must using `confirmOkText` option to change text:

```js
$('#cropImageBtn').bsModalCropper({
  id: 'bsModalCropper',
  title: 'Crop image',

  confirmOkText: 'Crop Now',
  ...
});
```

(This option is bad design... 😥)

**Comment by sajidfrommerqata** [comment]
@ycs77  thank you. working now 💖
