### ISSUE TITLE
How I can listen to Cancel button click?

### ISSUE THREAD

**Issue by sajidfrommerqata** [ycs77/jquery-plugin-bsModal#5]
How I can listen to the Cancel button click? I'm using **bsModalCropper** function. OnCancel is not working with me
https://prnt.sc/whiwyj

**Comment by ycs77** [comment]
Hello @sajidfrommerqata !

I released v1.1.1 to fixed this bug, you can update and try again 😅

**Comment by ycs77** [comment]
I will close this issue. If you has any problems, you can open the new issue.
