### ISSUE TITLE
Cropper js is dramatically increasing the file size after cropping

### ISSUE THREAD

**Issue by sajidfrommerqata** [ycs77/jquery-plugin-bsModal#6]
Hello

Hope you're doing well.

I found one issue in your code. The cropper js is dramatically increasing the file size after cropping. For more please read this link: Link: https://github.com/fengyuanchen/cropper/issues/542
Screenshot: https://prnt.sc/10b2e52
Where you should make this Change: https://prnt.sc/10b2f82

**Comment by ycs77** [comment]
Released v1.2.0 version!

**Comment by ycs77** [comment]
Read #8 for more information
